fitur_add_friend/urls.py
from django.conf.urls import url
from .views import index,add_friend,delete_friend,index_url_invalid

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^add_friend', add_friend, name='add_friend'),
    url(r'^url_invalid', index_url_invalid, name='url_invalid'),
    url(r'^(\d+)$', delete_friend, name='delete_friend')
]

fitur_halaman_profil/urls.py
from django.conf.urls import url
from .views import index

#url for app, add your URL Configuration

urlpatterns = [
#TODO Implement this
    url(r'^$', index, name='index'),
]

fitur_halaman_statistik/urls.py
from django.conf.urls import url
from .views import index

urlpatterns = [
    url(r'^$', index, name='index'),
]

fitur_update_status/urls.py
from django.conf.urls import url
from .views import StatusView

urlpatterns = [
    url(r'^$', StatusView.as_view(), name='index'),
]

tugas1/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import fitur_add_friend.urls as friends
import fitur_halaman_profil.urls as profil
import fitur_update_status.urls as status
import fitur_halaman_statistik.urls as statistik



urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^friend/', include(friends, namespace='friend')),
    url(r'^status/', include(status, namespace='status')),
    url(r'^', include(status, namespace='index')),
    url(r'^stats/', include(statistik, namespace='stats')),
    url(r'^profile/', include(profil, namespace='profile')),

]

fitur_add_friend/models.py
from django.db import models
from django.utils import timezone
import pytz

# Create your models here.
class Friend(models.Model):
    def convertTZ():
        return timezone.now()
    
    name = models.CharField(max_length=50)
    url = models.URLField()
    created_date = models.DateTimeField(default=convertTZ)

fitur_halaman_profil/models.py
from django.db import models

# Create your models here.

fitur_halaman_statistik/models.py
from django.db import models

# Create your models here.

fitur_update_status/models.py
from django.db import models
from tugas1.models import Profile
from tugas1.active_profile import get_active_profile

class StatusManager(models.Manager):
    '''
    Custom model manager for Status model, for easier query
    '''

    def get_newest(self):
        '''
        Returns the last inserted object, NOT based on it's timestamp
        Raises LookupError if there is no status at all
        '''
        if not self.all():
            raise LookupError()
        return self.all()[len(self.all()) - 1]


class Status(models.Model):
    message = models.TextField(max_length=256)
    user = models.ForeignKey(Profile, on_delete=models.PROTECT)
    post_date = models.DateTimeField(auto_now_add=True)
    objects = StatusManager()

    def __str__(self):
        return self.message + ' - ' + self.user.name

    def save(self, *args, **kwargs):
        '''
        Sets the user to active user
        '''
        self.user = get_active_profile()
        super(Status, self).save(*args, **kwargs)

tugas1/models.py
from django.db import models

class Profile(models.Model):
    name = models.CharField(max_length=64)
    email = models.EmailField()
    birth_date = models.DateField()
    expertise =  models.TextField() # comma-separated
    gender = models.CharField(max_length=8)
    description = models.CharField(max_length=256)
    picture_url = models.TextField()

    def __str__(self):
        return self.name + '(' + self.email + ')'
    

fitur_add_friend/forms.py
from django import forms

class Add_Friend_Form(forms.Form):
    error_messages = {
        'required': 'Tolong isi input ini',
        'invalid': 'isinya gak bener tong'
    }

    attrs = {
        'class': 'form-control'
    }

    name = forms.CharField(label='name', required=True, widget=forms.TextInput(attrs=attrs))
    url = forms.URLField(label='url', required=True, widget=forms.URLInput(attrs=attrs), initial='http://')

fitur_update_status/forms.py
from django.forms import ModelForm, Textarea
from .models import Status

class StatusForm(ModelForm):
    class Meta:
        model = Status
        fields = ('message',)
        error_messages = {
            'message': {
                'max_length': ("Status message is too long, max 256 characters."),
                'required': ("Status message cannot be empty")
            },
        }
        labels = {
            'message': ('Status Message'),
        }
        widgets = {
            'message': Textarea(attrs={'class':'form-control', 'rows':2}),
        }

fitur_add_friend/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .models import Friend
from .forms import Add_Friend_Form
import requests


response={}
def index(request):
    friend = Friend.objects.all()
    response['friend']= friend
    response['salah'] =False
    html = 'friend.html'
    response['add_friend_form'] = Add_Friend_Form
    response['page_friends'] = True
    return render(request, html, response)

def index_url_invalid(request):
    friend = Friend.objects.all()
    response['friend']= friend
    response['salah'] =True
    html = 'friend.html'
    response['add_friend_form'] = Add_Friend_Form
    response['page_friends'] = True
    return render(request, html, response)

def add_friend(request):
    form = Add_Friend_Form(request.POST or None)
    if(request.method == 'POST' and form.is_valid()):
        response['name'] = request.POST['name']
        response['url'] = request.POST['url']
        check = requests.get(response['url'])
        if(check.status_code == 404):
            return HttpResponseRedirect('/friend/url_invalid')
        friend = Friend(name=response['name'],url=response['url'])
        friend.save()
        return HttpResponseRedirect('/friend/')
    else:
        return HttpResponseRedirect('/friend/')

def delete_friend(request,data_id):
    friend = Friend.objects.get(id=data_id)
    friend.delete()
    return HttpResponseRedirect('/friend/')

fitur_halaman_profil/views.py
from django.shortcuts import render
from datetime import datetime, date
from tugas1.active_profile import get_active_profile


def index(request):
    profile = get_active_profile()
    response = {'name': profile.name,'description':profile.description, 'gender': profile.gender, 'email' : profile.email, 'birth' : profile.birth_date, 'expertise' : profile.expertise.split(','), 'picture' : profile.picture_url, 'page_profile' : True}
    return render(request, 'profile.html', response)

fitur_halaman_statistik/views.py
from django.shortcuts import render
from fitur_update_status.models import Status
from fitur_add_friend.models import Friend
from tugas1.active_profile import get_active_profile

# Create your views here.

def index(request):
	profile = get_active_profile()
	response = {}

	response['jumlah_status'] = Status.objects.count()
	try:
		response['status_terakhir'] = Status.objects.get_newest()
		response['jumlah_teman'] = Friend.objects.count()
		response['nama'] = profile.name
		response['page_stats'] = True
		response['picture'] = profile.picture_url
	except LookupError:
		pass #biar jadi null



	return render(request, 'stats.html',response)

fitur_update_status/views.py
from django.shortcuts import render
from django.views import View
from django.http import HttpResponseRedirect, HttpResponseBadRequest
from .models import Status
from tugas1.active_profile import get_active_profile
from .forms import StatusForm

class StatusView(View):
    MAX_STATUS_LENGTH = 256
    TEMPLATE = 'status.html'

    def get(self, request, new_status=False, form=None):
        '''
        Render the status page
        '''
        response = {}
        response['feed'] = []
        response['page_update_status'] = True
        for status in Status.objects.all():
            if status.user == get_active_profile():
                response['feed'].append(status)
        response['feed'] = response['feed'][::-1]
        status_code = 200
        if new_status:
            status_code = 201
        if form:
            response['form'] = form
            status_code = 400
        else:
            response['form'] = StatusForm()
        return render(request, StatusView.TEMPLATE, response, status=status_code)

    def post(self, request):
        '''
        Post new status as active user
        '''
        form = StatusForm(request.POST or None)
        # TODO: add error page
        if not form.is_valid():
            return self.get(request, form=form)
        else:
            form.save()
            return self.get(request, new_status=True)

fitur_add_friend/templates/friend.html
{% extends "base.html" %}
{% block content %}
<div class="animasi">
<section name="form" id="friendform">
    {% if salah %}
    <div class="container">
        <div class="alert alert-danger text-center" id="kuper">
            <strong>Maaf!</strong> URL yang anda masukan tidak ada.
        </div>
    </div>
    {% endif %}
    <div class="container">
        <h1 class="judul">Add Friend</h1>
        <form id="form" method="POST" action="{% url 'friend:add_friend' %}">
            {% csrf_token %}
            {{ add_friend_form }}
            <br>
            <button id="submit" type="submit" class="btn btn-default">Add Friend</button>
        </form>
    </div>
</section>

<section name="my-list" id="my-list">
    <div class="container">
        <h2 class="my-list-title">My Friends</h2>
        <div class="flex">
            {% if friend %}
                {% for data in friend %}
                    <div class="flex-item">
                        <div class="to-do-list">
                            <div class="gambar">
                                <img class='circletag' src="https://cdn0.iconfinder.com/data/icons/smile-emoticons/78/Emoticons_smile_smiley-16-512.png">
                            </div>
                            <div class="to-do-list-title">
                                {{data.name}}
                            </div>
                            <div class="to-do-list-date-added">
                                {{data.created_date}}
                            </div>
                            <div class="to-do-list-description">
                                <a href={{data.url}}>{{data.url}}</a>
                            </div>
                            <div class="to-do-list-delete">
                                <a style="color:white" href="{% url 'friend:delete_friend' data.id %}">
                                    <div class="to-do-list-delete-button" data-id="{{data.id}}">UnFriend</div>
                                </a>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            {% else %}
            <div class="alert alert-danger text-center" id="kuper">
                <strong>Yahh!</strong> Anda tidak punya teman.
            </div>
            {% endif %}
        </div>
    </div>
</section>
</div>
{% endblock %}

fitur_halaman_profil/templates/profile.html
{% extends "base.html" %}
{% block content %}
{% load static %}
<link href="{% static 'css/profile.css' %}" rel="stylesheet" />
<div class='container-fluid'>


<center>
<h1 class="h2">Profile</h1>
<h2 class="h2"></h2>
</center>


<img class="img-circle" style="width:150px; height:150px" src="{{ picture }}" />
    <h1> <center>{{ name }} </center></h1>
    <hr/>


<middle>
  <div>
    <ul class="expertise">
      {% for ii in expertise %}
      <li> {{ ii }} </li>
      {% endfor %}
    </ul>
  </div>

    <section class="container">
      <article>

  <div class = "row">
    <div class="col-sm-6" style="padding-left: 350px;">
        <h3>Birthday    </h3>
        <h3>Gender      </h3>
        <h3>Email       </h3>
        <h3>Description </h3>
    </div>

    <div class="col-sm-1">
        <h3>:</h3>
        <h3>:</h3>
        <h3>:</h3>
        <h3>:</h3>
    </div>

    <div class="col-sm-5">
        <h3>{{ birth }}</h3>
        <h3>{{ gender }}</h3>
        <h3>{{ email }}</h3>
        <h3>{{ description }}</h3>
    </div>
  </div>
  </article>
</section>

</middle>
</div>

{% endblock %}

fitur_halaman_statistik/templates/stats.html
{% extends "base.html" %}
{% block content %}
<div class="page-header" style="margin-left: 50px">
    <h2>Statistic</h2>
</div>

<div class="container">

	<div class="row">
	    <div class="col-sm-1">
			<img class="img-circle" style="width:200px; height:200px" src = "{{picture}}">
    	</div>
    	<div class="col-sm-4" style="margin-top: 70px ; margin-left: 150px">
	      	<h2> {{nama}} </h2>
	    </div>
	</div>

	<div class="row" style="margin-top: 50px">
		<div class="col-sm-2">
			<h3><b>Friends</b></h3>
		</div>

		<div class="col-sm-5">
			<h3>{{jumlah_teman}} People</h3>
		</div>


		<div class="col-sm-2">
			<h3><b>Feed</b></h3>
		</div>


		<div class="col-sm-2">
			<h3>{{jumlah_status}} Post</h3>
		</div>
	</div>

	<div class="row">
		<div class="col-sm-2">
			<h3>Latest Post</h3>
		</div>
	</div>

	{% if status_terakhir %}
		<div class="panel panel-default">
	        <div class="panel-heading">
	            <img class="img-rounded" width=32px height=32px src="{{status_terakhir.user.picture_url}}" />
	            <b>{{status_terakhir.user.name}}</b>
	        </div>
	        <div class="panel-body">
	        	{{status_terakhir.message|linebreaks}}
	        </div>
	        <div class="panel-footer">
	        	{{status_terakhir.post_date}}
	        </div>
	    </div>
	{% else %}
		<p>No Status Yet</p>
	{% endif %}


</div>
{% endblock %}

fitur_update_status/templates/status.html
{% extends "base.html" %}
{% block content %}

{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/update_status.css' %}">
<div class='container'>
    {% block update_form %}
    {% include "status_update.html" %}
    {% endblock %}
</div>

<div class='container'>
    {% block status_feed %}
    {% include "status_feed.html" %}
    {% endblock %}
</div>
{% endblock %}

fitur_update_status/templates/status_feed.html
<div class="page-header">
    <h2>Feed</h2>
</div>
<div class="container-fluid">
    {% if feed %}
    <div class="list-group">
        {% for status in feed %}
            <div class="panel panel-default">
                <div class="panel-heading">
                    <img class="img-rounded" width=32px height=32px src="{{status.user.picture_url}}" />
                    <b>{{status.user.name}}</b>
                </div>
                <div class="panel-body">{{status.message|linebreaks}}</div>
                <div class="panel-footer">{{status.post_date}}</div>
            </div>
        {% endfor %}
    </div>
    {% else %}
    <p>No status yet</p>
    {% endif %}
</div>

fitur_update_status/templates/status_update.html
<div class="page-header">
    <h2>Update Status</h2>
</div>
<div class="container-fluid">
    <!-- autosize the form (http://github.com/jackmoore/autosize) -->
    <script src="https://rawgit.com/jackmoore/autosize/master/dist/autosize.min.js"></script>
    <form action="{% url 'status:index' %}" method="POST">
        {% csrf_token %}
        {% for field in form %}

        <div class="container-fluid">
            <div class="form-group {% if field.errors %}has-error has-feedback{% endif %}">
                <div class="row">{{field.label_tag}}</div>
                <div class="row">
                        {{field}}
                        {% if field.errors %}<span class="glyphicon glyphicon-remove form-control-feedback"></span>{% endif %}
                    
                </div>
                <div class="row">{{field.errors}}</div>
            </div>
        </div>

        {% endfor %}
        <input type="submit" class="btn btn-default pull-right" value="Post" />
    </form>
    <script>
        autosize(document.querySelector('textarea'));          
    </script>
</div>

tugas1/templates/base.html
{% load staticfiles %}
{% load static %}
<!DOCTYPE html>
<html>
    <head>
          <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
          <link rel="stylesheet" type="text/css" href="{% static 'css/add_friend.css' %}" />
          <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}" />
    	    <title> {% block title %} Tugas 1 by Azhar, Raka, Wildan ,dan Yudhis{% endblock %} </title>
    </head>
    <body>
    <header>
		<nav class="navbar navbar-default">
		  <div class="container-fluid">
		    <div class="navbar-header">
		      <a class="navbar-brand" href="#">Ling In</a>
		    </div>

		    <ul class="nav navbar-nav">
		      <li class="nav-item {% if page_home %} active {% endif %}">
            <a href="/">Home</a>
          </li>

		      <li class="nav-item {% if page_update_status %} active {% endif %}">
            <a class="nav-link" href="/status/">Status</a>
          </li>

          <li class="nav-item {% if page_profile %} active {% endif %}">
            <a class="nav-link" href="/profile/">Profile</a>
          </li>

          <li class="nav-item {% if page_friends %} active {% endif %}">
            <a class="nav-link" href="/friend/">Friends</a>
          </li>

          <li class="nav-item {% if page_stats %} active {% endif %}">
            <a class="nav-link" href="/stats">Stats</a>
          </li>

		    </ul>
		  </div>
		</nav>    	
    </header>

        <content>
            {% block content %}
                <!-- content goes here -->
            {% endblock %}
        </content>

    <footer>
      <nav class="navbar navbar-default navbar-static-bottom" style="margin-bottom:-15px">
        <div class="container">
          <div class="navbar-header">
      	   <p class="navbar-brand">&copy; Made by Azhar, Raka, Wildan ,dan Yudhis</p>
          </div>
        </div>
      </nav>
    </footer>
  </body>
</html>